"""empty message

Revision ID: 097f3524f125
Revises: 2db01524c6fa
Create Date: 2026-07-28 10:38:59.702597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097f3524f125'
down_revision = '2db01524c6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('waiter_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['waiter_id'], ['waiter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
