"""empty message

Revision ID: 8b0467ad3601
Revises: 097f3524f125
Create Date: 2026-07-28 10:57:40.750220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0467ad3601'
down_revision = '097f3524f125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_table_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_waiter_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('order_waiter_id_fkey'), 'waiter', ['waiter_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('order_table_id_fkey'), 'table', ['table_id'], ['id'])

    # ### end Alembic commands ###
