"""empty message

Revision ID: a32ef145397c
Revises: e58c682a51d7
Create Date: 2026-07-29 14:56:00.720003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32ef145397c'
down_revision = 'e58c682a51d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_restaurant_chef', ['restaurant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.drop_constraint('unique_restaurant_chef', type_='unique')

    # ### end Alembic commands ###
