"""empty message

Revision ID: a6b596b4b700
Revises: 8b0467ad3601
Create Date: 2026-07-28 15:56:42.288167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b596b4b700'
down_revision = '8b0467ad3601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recipe_id')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
