"""empty message

Revision ID: e87df8cde3e4
Revises: 903e52872f7e
Create Date: 2026-08-07 08:54:30.044549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87df8cde3e4'
down_revision = '903e52872f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('chef_restaurant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cook', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cook_restaurant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('waiter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'waiter', ['waiter_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'table', ['table_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_restaurant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('waiter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('waiter_restaurant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('waiter_restaurant_id_fkey'), 'restaurant', ['restaurant_id'], ['id'])

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('restaurant_id')
        batch_op.drop_column('active')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_restaurant_id_fkey'), 'restaurant', ['restaurant_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('waiter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cook', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cook_restaurant_id_fkey'), 'restaurant', ['restaurant_id'], ['id'])

    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chef_restaurant_id_fkey'), 'restaurant', ['restaurant_id'], ['id'])
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('order_product')
    # ### end Alembic commands ###
